name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Vérification de la clé secrète avant d'exécuter les tests
    - name: Vérifier la clé secrète
      run: |
        echo "Vérification de la clé secrète..."
        if [ "${{ secrets.MY_SECRET_KEY }}" != "securite123" ]; then
          echo "Échec de la vérification du mot de passe !"
          exit 1  # Cela échouera le pipeline si la clé est incorrecte
        else
          echo "Clé secrète valide. Accès autorisé."
        fi

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python main.py


